services:
  floci:
    image: floci/floci:2.1.0@sha256:f5aa8c18302cedb4f2385f5c4e455b3efc77fee6bf7b6e5d1712b2817ba102db
    ports:
      - "4566:4566"
    environment:
      FLOCI_DEFAULT_REGION: us-east-1
      FLOCI_DEFAULT_ACCOUNT_ID: "000000000000"
      FLOCI_STORAGE_MODE: memory
      FLOCI_AUTH_VALIDATE_SIGNATURES: "true"
