services:
  floci-gcp:
    image: floci/floci-gcp:0.9.0@sha256:ea29a53b34d04ba05240cdc6833608e43ae2b0a67849e5b97f01a7224e1138ea
    ports:
      - "4588:4588"
    environment:
      FLOCI_GCP_HOSTNAME: localhost
      FLOCI_GCP_BASE_URL: http://localhost:4588
      FLOCI_GCP_STORAGE_MODE: memory
