// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: ping.proto

package hostproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_ping_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ping_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_ping_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SdkApiVersion string                 `protobuf:"bytes,1,opt,name=sdk_api_version,json=sdkApiVersion,proto3" json:"sdk_api_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_ping_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ping_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_ping_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetSdkApiVersion() string {
	if x != nil {
		return x.SdkApiVersion
	}
	return ""
}

type DescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_ping_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ping_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_ping_proto_rawDescGZIP(), []int{2}
}

type DescribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityJson  string                 `protobuf:"bytes,1,opt,name=identity_json,json=identityJson,proto3" json:"identity_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_ping_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ping_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_ping_proto_rawDescGZIP(), []int{3}
}

func (x *DescribeResponse) GetIdentityJson() string {
	if x != nil {
		return x.IdentityJson
	}
	return ""
}

type PlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestJson   string                 `protobuf:"bytes,1,opt,name=request_json,json=requestJson,proto3" json:"request_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanRequest) Reset() {
	*x = PlanRequest{}
	mi := &file_ping_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanRequest) ProtoMessage() {}

func (x *PlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ping_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanRequest.ProtoReflect.Descriptor instead.
func (*PlanRequest) Descriptor() ([]byte, []int) {
	return file_ping_proto_rawDescGZIP(), []int{4}
}

func (x *PlanRequest) GetRequestJson() string {
	if x != nil {
		return x.RequestJson
	}
	return ""
}

type PlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanJson      string                 `protobuf:"bytes,1,opt,name=plan_json,json=planJson,proto3" json:"plan_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanResponse) Reset() {
	*x = PlanResponse{}
	mi := &file_ping_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanResponse) ProtoMessage() {}

func (x *PlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ping_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanResponse.ProtoReflect.Descriptor instead.
func (*PlanResponse) Descriptor() ([]byte, []int) {
	return file_ping_proto_rawDescGZIP(), []int{5}
}

func (x *PlanResponse) GetPlanJson() string {
	if x != nil {
		return x.PlanJson
	}
	return ""
}

type ProgramRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanJson      string                 `protobuf:"bytes,1,opt,name=plan_json,json=planJson,proto3" json:"plan_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgramRequest) Reset() {
	*x = ProgramRequest{}
	mi := &file_ping_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramRequest) ProtoMessage() {}

func (x *ProgramRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ping_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramRequest.ProtoReflect.Descriptor instead.
func (*ProgramRequest) Descriptor() ([]byte, []int) {
	return file_ping_proto_rawDescGZIP(), []int{6}
}

func (x *ProgramRequest) GetPlanJson() string {
	if x != nil {
		return x.PlanJson
	}
	return ""
}

type ProgramResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultJson    string                 `protobuf:"bytes,1,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgramResponse) Reset() {
	*x = ProgramResponse{}
	mi := &file_ping_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramResponse) ProtoMessage() {}

func (x *ProgramResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ping_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramResponse.ProtoReflect.Descriptor instead.
func (*ProgramResponse) Descriptor() ([]byte, []int) {
	return file_ping_proto_rawDescGZIP(), []int{7}
}

func (x *ProgramResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecuteJson   string                 `protobuf:"bytes,1,opt,name=execute_json,json=executeJson,proto3" json:"execute_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_ping_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ping_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_ping_proto_rawDescGZIP(), []int{8}
}

func (x *ExecuteRequest) GetExecuteJson() string {
	if x != nil {
		return x.ExecuteJson
	}
	return ""
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultJson    string                 `protobuf:"bytes,1,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_ping_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ping_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_ping_proto_rawDescGZIP(), []int{9}
}

func (x *ExecuteResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

var File_ping_proto protoreflect.FileDescriptor

const file_ping_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"ping.proto\x12\x18magelift.providerhost.v1\"\r\n" +
	"\vPingRequest\"6\n" +
	"\fPingResponse\x12&\n" +
	"\x0fsdk_api_version\x18\x01 \x01(\tR\rsdkApiVersion\"\x11\n" +
	"\x0fDescribeRequest\"7\n" +
	"\x10DescribeResponse\x12#\n" +
	"\ridentity_json\x18\x01 \x01(\tR\fidentityJson\"0\n" +
	"\vPlanRequest\x12!\n" +
	"\frequest_json\x18\x01 \x01(\tR\vrequestJson\"+\n" +
	"\fPlanResponse\x12\x1b\n" +
	"\tplan_json\x18\x01 \x01(\tR\bplanJson\"-\n" +
	"\x0eProgramRequest\x12\x1b\n" +
	"\tplan_json\x18\x01 \x01(\tR\bplanJson\"2\n" +
	"\x0fProgramResponse\x12\x1f\n" +
	"\vresult_json\x18\x01 \x01(\tR\n" +
	"resultJson\"3\n" +
	"\x0eExecuteRequest\x12!\n" +
	"\fexecute_json\x18\x01 \x01(\tR\vexecuteJson\"2\n" +
	"\x0fExecuteResponse\x12\x1f\n" +
	"\vresult_json\x18\x01 \x01(\tR\n" +
	"resultJson2\xdb\x03\n" +
	"\bProvider\x12U\n" +
	"\x04Ping\x12%.magelift.providerhost.v1.PingRequest\x1a&.magelift.providerhost.v1.PingResponse\x12a\n" +
	"\bDescribe\x12).magelift.providerhost.v1.DescribeRequest\x1a*.magelift.providerhost.v1.DescribeResponse\x12U\n" +
	"\x04Plan\x12%.magelift.providerhost.v1.PlanRequest\x1a&.magelift.providerhost.v1.PlanResponse\x12^\n" +
	"\aProgram\x12(.magelift.providerhost.v1.ProgramRequest\x1a).magelift.providerhost.v1.ProgramResponse\x12^\n" +
	"\aExecute\x12(.magelift.providerhost.v1.ExecuteRequest\x1a).magelift.providerhost.v1.ExecuteResponseB>Z<github.com/magelift/magelift/internal/providerhost/hostprotob\x06proto3"

var (
	file_ping_proto_rawDescOnce sync.Once
	file_ping_proto_rawDescData []byte
)

func file_ping_proto_rawDescGZIP() []byte {
	file_ping_proto_rawDescOnce.Do(func() {
		file_ping_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ping_proto_rawDesc), len(file_ping_proto_rawDesc)))
	})
	return file_ping_proto_rawDescData
}

var file_ping_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_ping_proto_goTypes = []any{
	(*PingRequest)(nil),      // 0: magelift.providerhost.v1.PingRequest
	(*PingResponse)(nil),     // 1: magelift.providerhost.v1.PingResponse
	(*DescribeRequest)(nil),  // 2: magelift.providerhost.v1.DescribeRequest
	(*DescribeResponse)(nil), // 3: magelift.providerhost.v1.DescribeResponse
	(*PlanRequest)(nil),      // 4: magelift.providerhost.v1.PlanRequest
	(*PlanResponse)(nil),     // 5: magelift.providerhost.v1.PlanResponse
	(*ProgramRequest)(nil),   // 6: magelift.providerhost.v1.ProgramRequest
	(*ProgramResponse)(nil),  // 7: magelift.providerhost.v1.ProgramResponse
	(*ExecuteRequest)(nil),   // 8: magelift.providerhost.v1.ExecuteRequest
	(*ExecuteResponse)(nil),  // 9: magelift.providerhost.v1.ExecuteResponse
}
var file_ping_proto_depIdxs = []int32{
	0, // 0: magelift.providerhost.v1.Provider.Ping:input_type -> magelift.providerhost.v1.PingRequest
	2, // 1: magelift.providerhost.v1.Provider.Describe:input_type -> magelift.providerhost.v1.DescribeRequest
	4, // 2: magelift.providerhost.v1.Provider.Plan:input_type -> magelift.providerhost.v1.PlanRequest
	6, // 3: magelift.providerhost.v1.Provider.Program:input_type -> magelift.providerhost.v1.ProgramRequest
	8, // 4: magelift.providerhost.v1.Provider.Execute:input_type -> magelift.providerhost.v1.ExecuteRequest
	1, // 5: magelift.providerhost.v1.Provider.Ping:output_type -> magelift.providerhost.v1.PingResponse
	3, // 6: magelift.providerhost.v1.Provider.Describe:output_type -> magelift.providerhost.v1.DescribeResponse
	5, // 7: magelift.providerhost.v1.Provider.Plan:output_type -> magelift.providerhost.v1.PlanResponse
	7, // 8: magelift.providerhost.v1.Provider.Program:output_type -> magelift.providerhost.v1.ProgramResponse
	9, // 9: magelift.providerhost.v1.Provider.Execute:output_type -> magelift.providerhost.v1.ExecuteResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ping_proto_init() }
func file_ping_proto_init() {
	if File_ping_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ping_proto_rawDesc), len(file_ping_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ping_proto_goTypes,
		DependencyIndexes: file_ping_proto_depIdxs,
		MessageInfos:      file_ping_proto_msgTypes,
	}.Build()
	File_ping_proto = out.File
	file_ping_proto_goTypes = nil
	file_ping_proto_depIdxs = nil
}
